### PR TITLE
Fix/follow new html

### LINKED ISSUE #2: Skipping stops playback
## Cause
The bug seems to be caused by a change in the html structure

### PR DESCRIPTION
**Pull request by 0npv527yh9**
Fix #2 and refactor, such as method name changes, etc.

### CODE REVIEW

File: content.js [hunk 1]
```diff
@@ -55,23 +57,26 @@
     }
 
     function isPlaying() {
-        return document.querySelector('#stream-player .on') !== null;
+        return getToggleButton().getAttribute('data-elabel') == 'stop';
```
Comment (0npv527yh9) [inline content.js:60]: The main modification
